name: sv_dart_pi
description: Recebe os dados do firebase e insere no mysql
version: 1.0.0
# repository: https://github.com/kohrgeist/Projeto-Integrado---Modelagem-de-Dados

environment:
  sdk: ^3.9.4

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  mysql_client: ^0.0.27
  firedart: ^0.9.7
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
